CREATE TABLE EMPLOYEE

(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(6),
    SAL NUMBER(5),
    DEPTNO NUMBER(7)
);

INSERT INTO employee VALUES(1,'SUMEET','CODER',1000,01);
INSERT INTO EMPLOYEE (ename,job) values('bcdf','fact');
INSERT INTO EMPLOYEE (empno,ename,job) values(2,'bcdf','fact');

CREATE TABLE EMPLOYEE2

(
    EMPNO NUMBER(6),
    ENAME VARCHAR2(20),
    JOB VARCHAR2(6),
    SAL NUMBER(7),
    DEPTNO NUMBER(5),
    PRIMARY KEY(EMPNO,ENAME)
);

INSERT INTO employee2 VALUES(1,'SUMEET','SDW',1000,01);
INSERT INTO employee2 VALUES(2,'SUMEET','SDW',1000,01);
INSERT INTO employee2 VALUES(3,'legendsumeet','SDE',10000,01);


CREATE TABLE EMPOLYEE3
(
    EMPNO NUMBER(5),
    ENAME VARCHAR2(6),
    JOB VARCHAR2(6),
    SAL NUMBER(6),
    DEPTNO NUMBER(6)
);

ALTER TABLE EMPOLYEE3
ADD PRIMARY KEY(EMPNO);

CREATE TABLE DEPT
(
DEPTO NUMBER(2) PRIMARY KEY,
NAME VARCHAR2(20),
LOCATION VARCHAR(15)
);
