CREATE TABLE emp13(
    empno number,
    ename VARCHAR2(20)NOT NULL,
    design VARCHAR2(15),
    sal number(5),
);
INSERT INTO EMP13(EMPNO,DESIGN,SAL) VALUES(1,'HOD',100);
INSERT INTO EMP13(EMPNO,ENAME,DESIGN,SAL) VALUES(2,'HOD',100);
