
CREATE TABLE EMPLOYEE6

(
    EMPNO NUMBER(3),
    DEPTNO NUMBER(2),
    DESIGN VARCHAR2(10)
);

ALTER TABLE EMPLOYEE6 ADD
FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTO);

INSERT INTO employee6 VALUES (1,2,'SUMEET');
INSERT INTO employee6 VALUES (8,3,'SUMEET');
