CREATE TABLE DEPT1

(
    DEPTNO NUMBER(2),
    DNAME VARCHAR2(20),
    LOCATION VARCHAR2(15),
    PRIMARY KEY(DEPTNO,DNAME)
);

CREATE TABLE EMP5
(
    EMPNO NUMBER(3),
    DEPTNO NUMBER(2),
    DNAME VARCHAR(40),
    DESIGN VARCHAR2(10),
    FOREIGN KEY(DEPTNO,DNAME) REFERENCES DEPT1(DEPTNO,DNAME)
);


INSERT INTO dept1 VALUES(1,'SUMEET','MARS');
INSERT INTO dept1 VALUES(8,'SUMEET','MARS');
INSERT INTO dept1 VALUES(7,'SUMEETV','MARS');

INSERT INTO emp5 VALUES(1,8,'SUMEET','SWE');
INSERT INTO emp5 VALUES(2,7,'SUMEETV','SWD');
